### ISSUE TITLE
Segmentation fault on Example

### ISSUE THREAD

**Issue by troxtheone** [MrBhendel/Bleichenbacher-ECDSA-Nonce-Attack#2]
Hello, im getting a 'segmentation fault' running the example (output below).
I generated some sigs with randomSigGen.py, named the file 'rsmTuples', and run the example.
For the compilation, i installed libntl-dev and libfftw3-dev (v3.3.2-3.1).
```
debian-guest:~/Bleichenbacher-ECDSA-Nonce-Attack/example# gdb ./ex
[+] Loading (r,s,H(m)) tupples...
[+] Making (h,c) pairs for round 1...
[+] Starting sort & diff for round 1...
        545 pairs left.
[+] Finding top ten bias:MSB guesses for round 1...
Program received signal SIGSEGV, Segmentation fault.
0xb7d4542c in ?? () from /usr/lib/i386-linux-gnu/libfftw3.so.3
```
What could be the cause?

**Comment by MrBhendel** [comment]
Are you sure that you have enough memory in you computer to run libfftw’s malloc wrapper? If it can’t allocate enough memory for the DFT this is what happens. How much RAM do you have?
